version: "3.3"
networks:
  web:
    external: true
services:
    danilkinkin-landing:
        build: .
        restart: unless-stopped
        networks:
          - web
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.danilkinkin-landing.rule=Host(`danilkinkin.com`)"
          - "traefik.http.routers.danilkinkin-landing.entrypoints=web-http,web-https"
          - "traefik.http.routers.danilkinkin-landing.tls=true"
          - "traefik.http.routers.danilkinkin-landing.tls.certresolver=letsEncrypt"
          - "traefik.http.services.danilkinkin-landing-service.loadbalancer.server.port=80"
